const mongoose=require('mongoose')
const footerVideoSchema= new mongoose.Schema({
    footerVideo1:[{
        videoUrl:{
            type:String,
            required:true
        },
        videoFile:{
            type:String,
            required:true
        },
    }],
    footerVideo2:[{
        videoUrl:{
            type:String,
            required:true
        },
        videoFile:{
            type:String,
            required:true
        },
    }],
    footerVideo3:[{
        videoUrl:{
            type:String,
            required:true
        },
        videoFile:{
            type:String,
            required:true
        },
    }],
    footerBannerImage:{
        type:String,
        required:true
    }
})
const footerVideo=mongoose.model('footerVideo',footerVideoSchema)
module.exports=footerVideo